# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6788d235b968bba5d693bad30e2461584b9662aa6e4f6d691f41f9a66d80abe81b48ae8c5c06eb8d7f27507cac5d7ef35e3aece77bc12a2f77898db568033073

test:
  secret_key_base: 0dd6554abb22ea6ddb39198c1293fd84df1f742f980f51e899a4fed820db58f5195bb56660aa1969b12eaa864daf2edb0e54c28904837171ca911dd0ef27182d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
